export const DBFS_TMP_DIR_STATE_KEY = '__DATABRICKS_DBFS_TMP_DIR'
export const DBFS_UPLOAD_MAX_BYTES_PER_BLOCK = Math.pow(2, 20)
export const DATABRICKS_DBFS_DESTINATION_PATH_OUTPUT_KEY = 'dbfs-file-path'
